In [ ]:
!pip install pandas
!pip install pycaret
!pip install scikit-learn==1.2.2

In [1]:
import pandas as pd

In [2]:
ATT = pd.read_csv('/mnt/dataset/dataset-1982350335309512704/train.csv')

In [3]:
ATT

,ticket_id,ticket_type,strresnm,stripaddr,strifname,strifdesc,strifspeed,striftype,strifoperstatus,nren_id,...,fltbpsoutmax,fltppsinmax,fltppsoutmax,flterrorinmax,flterroroutmax,fltdiscardinmax,fltdiscardoutmax,fltunknownmax,fltusagemax,ai_accuracy
0,1493146,ATT2,busan-7712,NaN,CORE_ce1/1_부산-대전_100G,(5049)ce1/1,4294967295,ethernetCsmacd,up,NaN,...,0,0,0,0,0,0,0,0,0,0
1,1466236,ATT2,pangyo-5812,NaN,NREN_xe23_안양대학교_1G,(10023)xe23,1000000000,ethernetCsmacd,up,NaN,...,0,0,0,0,0,0,0,0,0,1
2,1465752,ATT2,pangyo-5812,NaN,NREN_xe31_용인세브란스병원_1G,(10031)xe31,1000000000,ethernetCsmacd,up,pangyo-5812_xe31,...,0,0,0,0,0,0,0,0,0,0
3,1466102,ATT2,busan-7712,NaN,CORE_ce1/1_부산-대전_100G,(5049)ce1/1,4294967295,ethernetCsmacd,up,NaN,...,0,0,0,0,0,0,0,0,0,0
4,1466721,ATT2,gwangju-7712,NaN,CORE_ce1/1_부산-대전_100G,(5049)ce1/1,4294967295,ethernetCsmacd,up,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,1443861,ATT2,seoul-7712,NaN,INTER_ce31/1_서울5812_40G,(5009)ce31/1,4294967295,ethernetCsmacd,up,NaN,...,0,0,0,0,0,0,0,0,0,1
336,1465789,ATT2,daegu-5812,NaN,NREN_xe22_순천향대학병원_1G,(5022)xe22,1000000000,ethernetCsmacd,up,NaN,...,0,0,0,0,0,0,0,0,0,1
337,1466513,ATT2,daegu-5812,NaN,NREN_xe23_안양대학교_1G,(10023)xe23,1000000000,ethernetCsmacd,up,daegu-5812_xe23,...,0,0,0,0,0,0,0,0,0,0
338,1465735,ATT2,daegu-5812,NaN,NREN_xe20_성균관대학교Lab_1G,(5020)xe20,1000000000,ethernetCsmacd,up,NaN,...,0,0,0,0,0,0,0,0,0,1
339,1466888,ATT2,daejeon-5812,NaN,NREN_xe25_자람테크놀로지_1G,(10025)xe25,1000000000,ethernetCsmacd,up,daejeon-5812_xe25,...,0,0,0,0,0,0,0,0,0,1

In [4]:
from ydata_profiling import ProfileReport
profile = ProfileReport(ATT, title="Profiling Report")
profile.to_file('ATT')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.8/dist-packages/ydata_profiling/profile_report.py:360: UserWarning: Extension  not supported. For now we assume .html was intended. To remove this warning, please use .html or .json.
  warnings.warn(

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
ATT.isnull().sum()

In [ ]:
ATT.nunique()

In [ ]:
(ATT.isnull().sum() / 340) * 100

In [ ]:
ATT['ticket_id'] = ATT['ticket_id'].astype('object')
ATT['strifid'] = ATT['strifid'].astype('object')
ATT['strresid'] = ATT['strresid'].astype('object')
ATT.info()

In [ ]:
import pandas as pd
import scipy.stats as stats

# Assuming ATT is your DataFrame

for col in ATT.columns:
    ctgr_list = ATT.select_dtypes(include='object').columns.tolist()
    num_list = ATT.select_dtypes(exclude='object').columns.tolist()
    num_list.remove('stripaddr')
    
    cond1 = ATT.nunique().reset_index()[0]==1
    nunique1 = ATT.nunique().reset_index().loc[cond1]['index'].tolist()
    for n in nunique1:
        if n in num_list:
            num_list.remove(n)
        
    num_list.remove('ai_accuracy')
    
#     if col in ctgr_list:
#         print('=' * 50)
#         print(col)
#         crosstab = pd.crosstab(ATT['ai_accuracy'], ATT[col])
#         display(crosstab)
#         chi2_stat, p_val, _, _ = stats.chi2_contingency(crosstab)
#         print(f'Chi-square Statistic: {chi2_stat}')
#         print(f'P-value: {p_val}')
#         if p_val < 0.05:
#             print('독립성을 띄지 않음')
#         else:
#             print('독립성을 띔')
        
#     print('=-'*50)

    if col in num_list:
        print(col)
        correlation_coefficient, p_value = stats.pearsonr(ATT[col], ATT['ai_accuracy'])

        # 결과 출력
        print(f"Pearson Correlation Coefficient: {correlation_coefficient}")
        print(f"P-value: {p_value}")

        # 유의수준에 따른 검정
        alpha = 0.05
        if p_value < alpha:
            print("귀무가설을 기각하고, 두 변수 간에는 통계적으로 유의한 상관관계가 있다.")
        else:
            print("귀무가설을 기각할 수 없으며, 두 변수 간에는 통계적으로 유의한 상관관계가 없다.")

In [ ]:
import pandas as pd
import scipy.stats as stats

time_list = ['intmonth', 'intday', 'inthour', 'intmin', 'intweek']


for col in time_list:
    print(col)
    correlation_coefficient, p_value = stats.pearsonr(ATT[col], ATT['inttimestamp'])

            # 결과 출력
    print(f"Pearson Correlation Coefficient: {correlation_coefficient}")
    print(f"P-value: {p_value}")

            # 유의수준에 따른 검정
    alpha = 0.05
    if p_value < alpha:
         print("귀무가설을 기각하고, 두 변수 간에는 통계적으로 유의한 상관관계가 있다.")
    else:
        print("귀무가설을 기각할 수 없으며, 두 변수 간에는 통계적으로 유의한 상관관계가 없다.")

In [ ]:
for i in ATT.columns:
    
    print('='*50)
    print(i)
    print(ATT[i].unique())

In [ ]:
ATT_nunique = ATT.nunique().reset_index()
drop_cols = []
# nunique 값이 1개
cond1 = ATT_nunique[0] <=1
cols = ATT_nunique.loc[cond1]['index'].tolist()
drop_cols = cols
for col in ATT.columns:
    if 'id' in col:
        drop_cols.append(col)
# isnull 값 139개 이상
ATT_isnull = ATT.isnull().sum().reset_index()
cond2 = ATT_isnull[0] > 139
cols = ATT_isnull.loc[cond2]['index'].tolist()
for col in cols:
    if col not in drop_cols:
        drop_cols.append

In [ ]:
ATT_processing = ATT.drop(columns=drop_cols)
ATT_processing

In [ ]:
ATT_processing.info()

In [ ]:
ATT_processing['nren_name'] = ATT_processing['nren_name'].fillna('-')

In [ ]:
# ATT_processing = ATT_processing.drop(columns='nren_name')

In [ ]:
ATT_processing

In [6]:
def pp(df_name):
    ATT = pd.read_csv(df_name)

    # 데이터 process
    ## 필요 없는 컬럼 삭제
    ATT_nunique = ATT.nunique().reset_index()
    drop_cols = []
    # nunique 값이 1개
    cond1 = ATT_nunique[0] <=1
    cols = ATT_nunique.loc[cond1]['index'].tolist()
    print(cols)
    drop_cols = cols
    for col in ATT.columns:
        if 'id' in col:
            drop_cols.append(col)
    
    # isnull 값 139개 이상
    ATT_isnull = ATT.isnull().sum().reset_index()
    cond2 = ATT_isnull[0] >= 139
    cols = ATT_isnull.loc[cond2]['index'].tolist()
    print(cols)
    for col in cols:
        if col not in drop_cols:
            drop_cols.append(col)
    print(drop_cols)
            
            
    ATT_processing = ATT.drop(columns=drop_cols)
    
    ATT_processing = ATT_processing.drop(columns=['intmonth','intday','inthour','intmin'])
    

    
    # 데이터 타입 설정
    ATT_processing = ATT_processing.astype('object')
    # test 할 떄만 ai_accuracy 변환
    ATT_processing['ai_accuracy'] = ATT_processing['ai_accuracy'].astype('int')
    ATT_processing['fltbpsin'] = ATT_processing['fltbpsin'].astype('int')
    ATT_processing['fltbpsout'] = ATT_processing['fltbpsout'].astype('int')
    ATT_processing['fltppsin'] = ATT_processing['fltppsin'].astype('int')
    ATT_processing['fltppsout'] = ATT_processing['fltppsout'].astype('int')
    ATT_processing['strifspeed'] = ATT_processing['strifspeed'].astype('int')

    
    # test 할 때만 ai_accuracy drop
#     ATT_processing = ATT_processing.drop(columns='ai_accuracy')
    
    
    return ATT_processing

In [7]:
ATT_processing = pp('/mnt/dataset/dataset-1982350335309512704/train.csv')

['ticket_type', 'stripaddr', 'striftype', 'strifoperstatus', 'strtypemin', 'intyear', 'intbandwidth', 'flterrorin', 'flterrorout', 'fltdiscardin', 'fltdiscardout', 'fltunknown', 'fltusage', 'flhcinoctets', 'flhcoutoctets', 'flhcinucastpkts', 'flhcoutucastpkts', 'flhcinmulticastpkts', 'flhcoutmulticastpkts', 'flhcinbroadcastpkts', 'flhcoutbroadcastpkts', 'fltbpsinmax', 'fltbpsoutmax', 'fltppsinmax', 'fltppsoutmax', 'flterrorinmax', 'flterroroutmax', 'fltdiscardinmax', 'fltdiscardoutmax', 'fltunknownmax', 'fltusagemax']
['stripaddr', 'nren_id', 'nren_name', 'node_id', 'if_id']
['ticket_type', 'stripaddr', 'striftype', 'strifoperstatus', 'strtypemin', 'intyear', 'intbandwidth', 'flterrorin', 'flterrorout', 'fltdiscardin', 'fltdiscardout', 'fltunknown', 'fltusage', 'flhcinoctets', 'flhcoutoctets', 'flhcinucastpkts', 'flhcoutucastpkts', 'flhcinmulticastpkts', 'flhcoutmulticastpkts', 'flhcinbroadcastpkts', 'flhcoutbroadcastpkts', 'fltbpsinmax', 'fltbpsoutmax', 'fltppsinmax', 'fltppsoutmax', 'flterrorinmax', 'flterroroutmax', 'fltdiscardinmax', 'fltdiscardoutmax', 'fltunknownmax', 'fltusagemax', 'ticket_id', 'nren_id', 'node_id', 'if_id', 'strifid', 'strresid', 'intbandwidth', 'nren_name']

In [8]:
ATT_processing

,strresnm,strifname,strifdesc,strifspeed,inttimestamp,intweek,fltbpsin,fltbpsout,fltppsin,fltppsout,ai_accuracy
0,busan-7712,CORE_ce1/1_부산-대전_100G,(5049)ce1/1,4294967295,1698733440,2,8,88,8365,10158,0
1,pangyo-5812,NREN_xe23_안양대학교_1G,(10023)xe23,1000000000,1693952820,3,0,0,0,0,1
2,pangyo-5812,NREN_xe31_용인세브란스병원_1G,(10031)xe31,1000000000,1693483080,4,259,285,28311,44843,0
3,busan-7712,CORE_ce1/1_부산-대전_100G,(5049)ce1/1,4294967295,1693898700,2,4,80,7802,8057,0
4,gwangju-7712,CORE_ce1/1_부산-대전_100G,(5049)ce1/1,4294967295,1694422320,1,12,0,1451,641,0
...,...,...,...,...,...,...,...,...,...,...,...
335,seoul-7712,INTER_ce31/1_서울5812_40G,(5009)ce31/1,4294967295,1689916800,5,492,-1849,127222,242119,1
336,daegu-5812,NREN_xe22_순천향대학병원_1G,(5022)xe22,1000000000,1693550160,5,0,0,0,0,1
337,daegu-5812,NREN_xe23_안양대학교_1G,(10023)xe23,1000000000,1694123040,5,0,0,0,0,0
338,daegu-5812,NREN_xe20_성균관대학교Lab_1G,(5020)xe20,1000000000,1693463940,4,0,0,33,34,1
339,daejeon-5812,NREN_xe25_자람테크놀로지_1G,(10025)xe25,1000000000,1694494380,2,0,0,10,22,1

In [ ]:
ATT[['strifname', 'nren_name']]

In [ ]:
ATT_processing

In [ ]:
ATT_processing.info()

In [ ]:
# 필요한 라이브러리 임포트
from pycaret.classification import *

# 1. 데이터셋 설정
clf2 = setup(data = ATT_processing, target ='ai_accuracy',index=False, session_id=10) # target column 이름을 지정해야 합니다.

# 2. 모델 비교

best_model = compare_models(sort='Accuracy') #10-92.43 #7836-91.14 #2904-90.69

In [ ]:
best_model.feature_names_in_

In [ ]:
tuned_model = tune_model(best_model)

In [ ]:
final_model = finalize_model(best_model)
final_model

In [ ]:
save_model(final_model, './submit_files/dt_model')

In [ ]:
model = load_model('dt_model')

In [ ]:
import sklearn
print(sklearn.__version__)

In [ ]:
f_imp = best_model.feature_importances_

In [ ]:
f_name = best_model.feature_names_in_

In [ ]:
df = pd.DataFrame()
df['name'] = f_name
df['importance'] = f_imp

In [ ]:
df.sort_values(by = 'importance', ascending=False)