In [ ]:
!pip install pandas
!pip install pycaret
!pip install ydata_profiling
!pip install scikit-learn==1.2.2

In [ ]:
import sklearn
print(sklearn.__version__)

In [1]:
import pandas as pd

In [2]:
NTT = pd.read_csv('/mnt/dataset/dataset-1967120043485429760/train.csv')
NTT

,ticket_id,ticket_type,strresnum,strresip,strresname,strs_ip,strs_port,strd_ip,strd_port,strs_mac,...,strprotocol,stripv4tos,strchannel,strsenderip,strin_interface,strout_interface,strbytes_col,strcounts,dateregdate,ai_accuracy
0,1465461,NTT,NaN,61.252.50.11,pangyo-7712,203.255.254.21,29868,23.67.53.153,443,34-EF-B6-0A-91-33,...,6,0,HTTPS,116.89.169.31,NaN,NaN,648192,1,49:55.0,1
1,740633,NTT,NaN,61.252.50.3,daejeon-7712,61.252.59.12,5201,45.248.72.2,53300,3C-2C-99-2B-6C-AD,...,6,0,Other TCP,116.89.169.21,NaN,NaN,23932928,449,44:54.0,0
2,865310,NTT,NaN,61.252.50.1,seoul-7712,61.252.59.7,5201,45.248.72.2,46410,70-DB-98-D9-CF-E7,...,6,0,Other TCP,116.89.169.11,NaN,NaN,19705856,368,49:54.0,0
3,1135235,NTT,NaN,61.252.50.11,pangyo-7712,40.100.50.114,443,203.255.254.21,52433,3C-2C-99-2B-6C-AD,...,17,0,Other UDP,116.89.169.31,NaN,NaN,0,1,24:54.0,0
4,1466752,NTT,NaN,61.252.50.11,pangyo-7712,210.114.91.91,26379,125.178.168.30,7650,34-EF-B6-0A-91-33,...,6,8,Other TCP,116.89.169.31,NaN,NaN,10432512,183,39:55.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5101,1433725,NTT,NaN,61.252.50.11,pangyo-7712,203.255.254.21,57817,203.133.162.210,443,34-EF-B6-0A-91-33,...,6,0,HTTPS,116.89.169.31,NaN,NaN,5185536,126,49:54.0,1
5102,1443476,NTT,NaN,61.252.50.11,pangyo-7712,3.36.116.7,17683,203.255.254.108,8083,3C-2C-99-2B-6C-AD,...,6,0,Other TCP,116.89.169.31,NaN,NaN,0,1,29:54.0,1
5103,874667,NTT,NaN,61.252.50.3,daejeon-7712,61.252.59.17,5201,45.248.72.2,47454,3C-2C-99-2B-6C-AD,...,6,0,Other TCP,116.89.169.21,NaN,NaN,12619776,237,34:54.0,0
5104,1434199,NTT,NaN,61.252.50.11,pangyo-7712,203.255.253.230,54887,20.42.65.88,443,34-EF-B6-0A-91-33,...,6,2,HTTPS,116.89.169.31,NaN,NaN,648192,1,09:54.0,1
5105,1377248,NTT,NaN,61.252.50.5,daegu-7712,116.89.170.11,179,116.89.170.53,46604,3C-2C-99-2B-6C-AD,...,6,192,Other TCP,116.89.169.51,NaN,NaN,0,1,24:56.0,1

In [3]:
NTT.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5106 entries, 0 to 5105
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ticket_id         5106 non-null   int64
 1   ticket_type       5106 non-null   object
 2   strresnum         1 non-null      float64
 3   strresip          5106 non-null   object
 4   strresname        5106 non-null   object
 5   strs_ip           5106 non-null   object
 6   strs_port         5106 non-null   int64
 7   strd_ip           5106 non-null   object
 8   strd_port         5106 non-null   int64
 9   strs_mac          5106 non-null   object
 10  strd_mac          5106 non-null   object
 11  strprotocol       5106 non-null   int64
 12  stripv4tos        5106 non-null   int64
 13  strchannel        5106 non-null   object
 14  strsenderip       5106 non-null   object
 15  strin_interface   1 non-null      object
 16  strout_interface  0 non-null      float64
 17  strbytes_col      5106 non-null   int64
 18  strcounts         5106 non-null   int64
 19  dateregdate       5106 non-null   object
 20  ai_accuracy       5106 non-null   int64
dtypes: float64(2), int64(8), object(11)
memory usage: 837.8+ KB

In [4]:
NTT.nunique()

ticket_id           5094
ticket_type            1
strresnum              1
strresip               6
strresname             6
strs_ip              791
strs_port           2496
strd_ip              985
strd_port           2235
strs_mac              34
strd_mac              22
strprotocol            2
stripv4tos            16
strchannel            14
strsenderip            6
strin_interface        1
strout_interface       0
strbytes_col        1034
strcounts            481
dateregdate           48
ai_accuracy            2
dtype: int64

In [5]:
NTT.isnull().sum()

ticket_id              0
ticket_type            0
strresnum           5105
strresip               0
strresname             0
strs_ip                0
strs_port              0
strd_ip                0
strd_port              0
strs_mac               0
strd_mac               0
strprotocol            0
stripv4tos             0
strchannel             0
strsenderip            0
strin_interface     5105
strout_interface    5106
strbytes_col           0
strcounts              0
dateregdate            0
ai_accuracy            0
dtype: int64

In [6]:
(NTT.isnull().sum()/ 5106)*100

ticket_id             0.000000
ticket_type           0.000000
strresnum            99.980415
strresip              0.000000
strresname            0.000000
strs_ip               0.000000
strs_port             0.000000
strd_ip               0.000000
strd_port             0.000000
strs_mac              0.000000
strd_mac              0.000000
strprotocol           0.000000
stripv4tos            0.000000
strchannel            0.000000
strsenderip           0.000000
strin_interface      99.980415
strout_interface    100.000000
strbytes_col          0.000000
strcounts             0.000000
dateregdate           0.000000
ai_accuracy           0.000000
dtype: float64

In [7]:
NTT['ticket_id'] = NTT['ticket_id'].astype('object')
NTT.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5106 entries, 0 to 5105
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ticket_id         5106 non-null   object
 1   ticket_type       5106 non-null   object
 2   strresnum         1 non-null      float64
 3   strresip          5106 non-null   object
 4   strresname        5106 non-null   object
 5   strs_ip           5106 non-null   object
 6   strs_port         5106 non-null   int64
 7   strd_ip           5106 non-null   object
 8   strd_port         5106 non-null   int64
 9   strs_mac          5106 non-null   object
 10  strd_mac          5106 non-null   object
 11  strprotocol       5106 non-null   int64
 12  stripv4tos        5106 non-null   int64
 13  strchannel        5106 non-null   object
 14  strsenderip       5106 non-null   object
 15  strin_interface   1 non-null      object
 16  strout_interface  0 non-null      float64
 17  strbytes_col      5106 non-null   int64
 18  strcounts         5106 non-null   int64
 19  dateregdate       5106 non-null   object
 20  ai_accuracy       5106 non-null   int64
dtypes: float64(2), int64(7), object(12)
memory usage: 837.8+ KB

In [8]:
NTT.describe()

,strresnum,strs_port,strd_port,strprotocol,stripv4tos,strout_interface,strbytes_col,strcounts,ai_accuracy
count,1.000000e+00,5106.000000,5106.000000,5106.000000,5106.000000,0.0,5.106000e+03,5106.000000,5106.000000
mean,1.623830e+12,23819.866432,22665.427145,7.322758,20.786134,NaN,4.188462e+06,79.632002,0.644928
std,NaN,22679.492575,23133.616778,3.578149,58.444734,NaN,1.130466e+07,219.056172,0.478582
min,1.623830e+12,22.000000,21.000000,6.000000,0.000000,NaN,0.000000e+00,1.000000,0.000000
25%,1.623830e+12,862.000000,443.000000,6.000000,0.000000,NaN,0.000000e+00,1.000000,0.000000
50%,1.623830e+12,11689.000000,10001.000000,6.000000,0.000000,NaN,0.000000e+00,1.000000,1.000000
75%,1.623830e+12,47086.750000,46553.750000,6.000000,0.000000,NaN,6.492160e+05,1.000000,1.000000
max,1.623830e+12,65522.000000,65489.000000,17.000000,192.000000,NaN,2.524037e+08,5639.000000,1.000000

In [9]:
NTT.describe(include='object')

,ticket_id,ticket_type,strresip,strresname,strs_ip,strd_ip,strs_mac,strd_mac,strchannel,strsenderip,strin_interface,dateregdate
count,5106,5106,5106,5106,5106,5106,5106,5106,5106,5106,1,5106
unique,5094,1,6,6,791,985,34,22,14,6,1,48
top,1118536,NTT,61.252.50.11,pangyo-7712,203.255.254.21,45.248.72.2,3C-2C-99-2B-6C-AD,3C-2C-99-5F-6C-D3,Other TCP,116.89.169.31,INTER_Eth1/1_서울ASR9K_10G,29:55.0
freq,4,5106,2522,2522,559,477,1735,2281,2135,2522,1,1155

In [10]:
import pandas as pd
import scipy.stats as stats

# Assuming ATT is your DataFrame

for col in NTT.columns:
    ctgr_list = NTT.select_dtypes(include='object').columns.tolist()
    num_list = NTT.select_dtypes(exclude='object').columns.tolist()
    
    cond1 = NTT.nunique().reset_index()[0]==1
    nunique1 = NTT.nunique().reset_index().loc[cond1]['index'].tolist()
    for n in nunique1:
        if n in num_list:
            num_list.remove(n)
            
    num_list.remove('strout_interface')
    num_list.remove('ai_accuracy')
    
#     if col in ctgr_list:
#         print('=' * 50)
#         print(col)
#         crosstab = pd.crosstab(NTT['ai_accuracy'], NTT[col])
#         display(crosstab)
#         chi2_stat, p_val, _, _ = stats.chi2_contingency(crosstab)
#         print(f'Chi-square Statistic: {chi2_stat}')
#         print(f'P-value: {p_val}')
#         if p_val < 0.05:
#             print('독립성을 띄지 않음')
#         else:
#             print('독립성을 띔')
        
#     print('=-'*50)

    if col in num_list:
        print(col)
        correlation_coefficient, p_value = stats.pearsonr(NTT[col], NTT['ai_accuracy'])

        # 결과 출력
        print(f"Pearson Correlation Coefficient: {correlation_coefficient}")
        print(f"P-value: {p_value}")

        # 유의수준에 따른 검정
        alpha = 0.05
        if p_value < alpha:
            print("귀무가설을 기각하고, 두 변수 간에는 통계적으로 유의한 상관관계가 있다.")
        else:
            print("귀무가설을 기각할 수 없으며, 두 변수 간에는 통계적으로 유의한 상관관계가 없다.")

strs_port
Pearson Correlation Coefficient: 0.14702095756707284
P-value: 4.5457524088463747e-26
귀무가설을 기각하고, 두 변수 간에는 통계적으로 유의한 상관관계가 있다.
strd_port
Pearson Correlation Coefficient: -0.14285094146610883
P-value: 1.0922831407810835e-24
귀무가설을 기각하고, 두 변수 간에는 통계적으로 유의한 상관관계가 있다.
strprotocol
Pearson Correlation Coefficient: 0.042800218147072674
P-value: 0.0022207917102954875
귀무가설을 기각하고, 두 변수 간에는 통계적으로 유의한 상관관계가 있다.
stripv4tos
Pearson Correlation Coefficient: 0.018791665511202565
P-value: 0.1794105067325901
귀무가설을 기각할 수 없으며, 두 변수 간에는 통계적으로 유의한 상관관계가 없다.
strbytes_col
Pearson Correlation Coefficient: -0.2910762834168329
P-value: 2.898934406166783e-100
귀무가설을 기각하고, 두 변수 간에는 통계적으로 유의한 상관관계가 있다.
strcounts
Pearson Correlation Coefficient: -0.27763648459329066
P-value: 5.008711805170854e-91
귀무가설을 기각하고, 두 변수 간에는 통계적으로 유의한 상관관계가 있다.

In [84]:
from ydata_profiling import ProfileReport
profile = ProfileReport(NTT, title="Profiling Report")
profile.to_file('NTT')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [12]:
NTT_nunique=NTT.nunique().reset_index()
drop_cols=[]
cond1 = NTT_nunique[0]<=1
cols = NTT_nunique.loc[cond1]['index'].tolist()
print(cols)
# drop_cols = cols
# for col in NTT.columns:
#     if 'id' in col:
#         drop_cols.append(col)
NTT_isnull = NTT.isnull().sum().reset_index()
cond2=NTT_isnull[0]>25
cols=NTT_isnull.loc[cond2]['index'].tolist()
print(cols)
for col in cols:
    if col not in drop_cols:
        drop_cols.append(col)
drop_cols

['ticket_type', 'strresnum', 'strin_interface', 'strout_interface']
['strresnum', 'strin_interface', 'strout_interface']

['strresnum', 'strin_interface', 'strout_interface']

In [22]:
NTT_processing = NTT.drop(columns=drop_cols)
NTT_processing

,ticket_id,ticket_type,strresip,strresname,strs_ip,strs_port,strd_ip,strd_port,strs_mac,strd_mac,strprotocol,stripv4tos,strchannel,strsenderip,strbytes_col,strcounts,dateregdate,ai_accuracy
0,1465461,NTT,61.252.50.11,pangyo-7712,203.255.254.21,29868,23.67.53.153,443,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,0,HTTPS,116.89.169.31,648192,1,49:55.0,1
1,740633,NTT,61.252.50.3,daejeon-7712,61.252.59.12,5201,45.248.72.2,53300,3C-2C-99-2B-6C-AD,3C-2C-99-D1-96-60,6,0,Other TCP,116.89.169.21,23932928,449,44:54.0,0
2,865310,NTT,61.252.50.1,seoul-7712,61.252.59.7,5201,45.248.72.2,46410,70-DB-98-D9-CF-E7,3C-2C-99-2B-6C-AD,6,0,Other TCP,116.89.169.11,19705856,368,49:54.0,0
3,1135235,NTT,61.252.50.11,pangyo-7712,40.100.50.114,443,203.255.254.21,52433,3C-2C-99-2B-6C-AD,3C-2C-99-5F-6C-D3,17,0,Other UDP,116.89.169.31,0,1,24:54.0,0
4,1466752,NTT,61.252.50.11,pangyo-7712,210.114.91.91,26379,125.178.168.30,7650,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,8,Other TCP,116.89.169.31,10432512,183,39:55.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5101,1433725,NTT,61.252.50.11,pangyo-7712,203.255.254.21,57817,203.133.162.210,443,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,0,HTTPS,116.89.169.31,5185536,126,49:54.0,1
5102,1443476,NTT,61.252.50.11,pangyo-7712,3.36.116.7,17683,203.255.254.108,8083,3C-2C-99-2B-6C-AD,3C-2C-99-5F-6C-D3,6,0,Other TCP,116.89.169.31,0,1,29:54.0,1
5103,874667,NTT,61.252.50.3,daejeon-7712,61.252.59.17,5201,45.248.72.2,47454,3C-2C-99-2B-6C-AD,3C-2C-99-D1-96-60,6,0,Other TCP,116.89.169.21,12619776,237,34:54.0,0
5104,1434199,NTT,61.252.50.11,pangyo-7712,203.255.253.230,54887,20.42.65.88,443,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,2,HTTPS,116.89.169.31,648192,1,09:54.0,1
5105,1377248,NTT,61.252.50.5,daegu-7712,116.89.170.11,179,116.89.170.53,46604,3C-2C-99-2B-6C-AD,3C-2C-99-33-53-50,6,192,Other TCP,116.89.169.51,0,1,24:56.0,1

In [23]:
# NTT_processing =  NTT_processing.astype('object')
# NTT_processing['ai_accuracy'] = NTT_processing['ai_accuracy'].astype('int')

In [24]:
NTT_processing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5106 entries, 0 to 5105
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ticket_id     5106 non-null   object
 1   ticket_type   5106 non-null   object
 2   strresip      5106 non-null   object
 3   strresname    5106 non-null   object
 4   strs_ip       5106 non-null   object
 5   strs_port     5106 non-null   int64
 6   strd_ip       5106 non-null   object
 7   strd_port     5106 non-null   int64
 8   strs_mac      5106 non-null   object
 9   strd_mac      5106 non-null   object
 10  strprotocol   5106 non-null   int64
 11  stripv4tos    5106 non-null   int64
 12  strchannel    5106 non-null   object
 13  strsenderip   5106 non-null   object
 14  strbytes_col  5106 non-null   int64
 15  strcounts     5106 non-null   int64
 16  dateregdate   5106 non-null   object
 17  ai_accuracy   5106 non-null   int64
dtypes: int64(7), object(11)
memory usage: 718.2+ KB

In [25]:
def func1(df):
    return df.split('-')[0]

In [26]:
NTT_processing['strresname'] = NTT_processing['strresname'].apply(func1)

In [27]:
NTT_processing = NTT_processing.drop(columns=['strs_port','strd_port','strbytes_col','strd_ip','strs_ip','dateregdate', 'stripv4tos'])

In [17]:
NTT_processing

,ticket_id,ticket_type,strresip,strresname,strs_mac,strd_mac,strprotocol,strchannel,strsenderip,strcounts,ai_accuracy
0,1465461,NTT,61.252.50.11,pangyo,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,HTTPS,116.89.169.31,1,1
1,740633,NTT,61.252.50.3,daejeon,3C-2C-99-2B-6C-AD,3C-2C-99-D1-96-60,6,Other TCP,116.89.169.21,449,0
2,865310,NTT,61.252.50.1,seoul,70-DB-98-D9-CF-E7,3C-2C-99-2B-6C-AD,6,Other TCP,116.89.169.11,368,0
3,1135235,NTT,61.252.50.11,pangyo,3C-2C-99-2B-6C-AD,3C-2C-99-5F-6C-D3,17,Other UDP,116.89.169.31,1,0
4,1466752,NTT,61.252.50.11,pangyo,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,Other TCP,116.89.169.31,183,1
...,...,...,...,...,...,...,...,...,...,...,...
5101,1433725,NTT,61.252.50.11,pangyo,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,HTTPS,116.89.169.31,126,1
5102,1443476,NTT,61.252.50.11,pangyo,3C-2C-99-2B-6C-AD,3C-2C-99-5F-6C-D3,6,Other TCP,116.89.169.31,1,1
5103,874667,NTT,61.252.50.3,daejeon,3C-2C-99-2B-6C-AD,3C-2C-99-D1-96-60,6,Other TCP,116.89.169.21,237,0
5104,1434199,NTT,61.252.50.11,pangyo,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,HTTPS,116.89.169.31,1,1
5105,1377248,NTT,61.252.50.5,daegu,3C-2C-99-2B-6C-AD,3C-2C-99-33-53-50,6,Other TCP,116.89.169.51,1,1

In [18]:
NTT_processing

,ticket_id,ticket_type,strresip,strresname,strs_mac,strd_mac,strprotocol,strchannel,strsenderip,strcounts,ai_accuracy
0,1465461,NTT,61.252.50.11,pangyo,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,HTTPS,116.89.169.31,1,1
1,740633,NTT,61.252.50.3,daejeon,3C-2C-99-2B-6C-AD,3C-2C-99-D1-96-60,6,Other TCP,116.89.169.21,449,0
2,865310,NTT,61.252.50.1,seoul,70-DB-98-D9-CF-E7,3C-2C-99-2B-6C-AD,6,Other TCP,116.89.169.11,368,0
3,1135235,NTT,61.252.50.11,pangyo,3C-2C-99-2B-6C-AD,3C-2C-99-5F-6C-D3,17,Other UDP,116.89.169.31,1,0
4,1466752,NTT,61.252.50.11,pangyo,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,Other TCP,116.89.169.31,183,1
...,...,...,...,...,...,...,...,...,...,...,...
5101,1433725,NTT,61.252.50.11,pangyo,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,HTTPS,116.89.169.31,126,1
5102,1443476,NTT,61.252.50.11,pangyo,3C-2C-99-2B-6C-AD,3C-2C-99-5F-6C-D3,6,Other TCP,116.89.169.31,1,1
5103,874667,NTT,61.252.50.3,daejeon,3C-2C-99-2B-6C-AD,3C-2C-99-D1-96-60,6,Other TCP,116.89.169.21,237,0
5104,1434199,NTT,61.252.50.11,pangyo,34-EF-B6-0A-91-33,3C-2C-99-5F-6C-D3,6,HTTPS,116.89.169.31,1,1
5105,1377248,NTT,61.252.50.5,daegu,3C-2C-99-2B-6C-AD,3C-2C-99-33-53-50,6,Other TCP,116.89.169.51,1,1

In [31]:
NTT_processing[['smac1','smac2','smac3','smac4', 'smac5', 'smac6']] = NTT_processing['strs_mac'].str.rsplit('-', expand=True)

In [32]:
 NTT_processing[['dmac1','dmac2','dmac3','dmac4', 'dmac5', 'dmac6']] = NTT_processing['strd_mac'].str.rsplit('-', expand=True)

In [33]:
NTT_processing = NTT_processing.drop(columns=['strs_mac','strd_mac'])

In [49]:
NTT_processing

,ticket_id,ticket_type,strresip,strresname,strprotocol,strchannel,strsenderip,strcounts,ai_accuracy,smac1,...,smac3,smac4,smac5,smac6,dmac1,dmac2,dmac3,dmac4,dmac5,dmac6
0,1465461,NTT,61.252.50.11,pangyo,6,HTTPS,116.89.169.31,1,1,34,...,B6,0A,91,33,3C,2C,99,5F,6C,D3
1,740633,NTT,61.252.50.3,daejeon,6,Other TCP,116.89.169.21,449,0,3C,...,99,2B,6C,AD,3C,2C,99,D1,96,60
2,865310,NTT,61.252.50.1,seoul,6,Other TCP,116.89.169.11,368,0,70,...,98,D9,CF,E7,3C,2C,99,2B,6C,AD
3,1135235,NTT,61.252.50.11,pangyo,17,Other UDP,116.89.169.31,1,0,3C,...,99,2B,6C,AD,3C,2C,99,5F,6C,D3
4,1466752,NTT,61.252.50.11,pangyo,6,Other TCP,116.89.169.31,183,1,34,...,B6,0A,91,33,3C,2C,99,5F,6C,D3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5101,1433725,NTT,61.252.50.11,pangyo,6,HTTPS,116.89.169.31,126,1,34,...,B6,0A,91,33,3C,2C,99,5F,6C,D3
5102,1443476,NTT,61.252.50.11,pangyo,6,Other TCP,116.89.169.31,1,1,3C,...,99,2B,6C,AD,3C,2C,99,5F,6C,D3
5103,874667,NTT,61.252.50.3,daejeon,6,Other TCP,116.89.169.21,237,0,3C,...,99,2B,6C,AD,3C,2C,99,D1,96,60
5104,1434199,NTT,61.252.50.11,pangyo,6,HTTPS,116.89.169.31,1,1,34,...,B6,0A,91,33,3C,2C,99,5F,6C,D3
5105,1377248,NTT,61.252.50.5,daegu,6,Other TCP,116.89.169.51,1,1,3C,...,99,2B,6C,AD,3C,2C,99,33,53,50

In [101]:
def func1(df):
    return df.split('-')[0]

def func2(df):
    dataframe['smac1'] = df.split('-')[0]
    dataframe['smac2'] = df.split('-')[1]
    dataframe['smac3'] = df.split('-')[2]
    dataframe['smac4'] = df.split('-')[3]


def func3(df):
    NTT_processing['dmac1'] = df.split('-')[0]
    NTT_processing['dmac2'] = df.split('-')[1]
    NTT_processing['dmac3'] = df.split('-')[2]
    NTT_processing['dmac4'] = df.split('-')[3]
    return e, f, g, h

def pp(df_name):
    NTT = pd.read_csv(df_name)

    NTT_nunique=NTT.nunique().reset_index()
    drop_cols=[]
    cond1 = NTT_nunique[0]<=1
    cols = NTT_nunique.loc[cond1]['index'].tolist()
#     drop_cols = cols
#     for col in NTT.columns:
#         if 'id' in col:
#             drop_cols.append(col)
    NTT_isnull = NTT.isnull().sum().reset_index()
    cond2=NTT_isnull[0]>22
    cols=NTT_isnull.loc[cond2]['index'].tolist()
    for col in cols:
        if col not in drop_cols:
            drop_cols.append(col)
            
    print(drop_cols)
    NTT_processing = NTT.drop(columns=drop_cols)
    
    NTT_processing = NTT_processing.drop(columns=['ticket_id','ticket_type'])
    
    NTT_processing = NTT_processing.astype('object')
    
    NTT_processing['strresname'] = NTT_processing['strresname'].apply(func1)
    
    NTT_processing = NTT_processing.drop(columns=['strs_port','strd_port','strbytes_col','strd_ip','strs_ip','dateregdate', 'stripv4tos'])
    
    NTT_processing[['smac1','smac2','smac3','smac4', 'smac5', 'smac6']] = NTT_processing['strs_mac'].str.rsplit('-', expand=True)

    NTT_processing[['dmac1','dmac2','dmac3','dmac4', 'dmac5', 'dmac6']] = NTT_processing['strd_mac'].str.rsplit('-', expand=True)
    
    
#     NTT_processing = NTT_processing.drop(columns=['strs_mac','strd_mac'])
    
#     NTT_processing = NTT_processing.drop(columns='ai_accuracy')
    
    # test용 전처리
    NTT_processing['ai_accuracy'] = NTT_processing['ai_accuracy'].astype('int')
    print(NTT_processing.columns)

    return NTT_processing
# test용
NTT_processing = pp('/mnt/dataset/dataset-1967120043485429760/train.csv')

# 실제 submit용
# X_test=pp('/mnt/dataset/test.csv')

['strresnum', 'strin_interface', 'strout_interface']
Index(['strresip', 'strresname', 'strs_mac', 'strd_mac', 'strprotocol',
       'strchannel', 'strsenderip', 'strcounts', 'ai_accuracy', 'smac1',
       'smac2', 'smac3', 'smac4', 'smac5', 'smac6', 'dmac1', 'dmac2', 'dmac3',
       'dmac4', 'dmac5', 'dmac6'],
      dtype='object')

In [102]:
NTT_processing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5106 entries, 0 to 5105
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   strresip     5106 non-null   object
 1   strresname   5106 non-null   object
 2   strs_mac     5106 non-null   object
 3   strd_mac     5106 non-null   object
 4   strprotocol  5106 non-null   object
 5   strchannel   5106 non-null   object
 6   strsenderip  5106 non-null   object
 7   strcounts    5106 non-null   object
 8   ai_accuracy  5106 non-null   int64
 9   smac1        5106 non-null   object
 10  smac2        5106 non-null   object
 11  smac3        5106 non-null   object
 12  smac4        5106 non-null   object
 13  smac5        5106 non-null   object
 14  smac6        5106 non-null   object
 15  dmac1        5106 non-null   object
 16  dmac2        5106 non-null   object
 17  dmac3        5106 non-null   object
 18  dmac4        5106 non-null   object
 19  dmac5        5106 non-null   object
 20  dmac6        5106 non-null   object
dtypes: int64(1), object(20)
memory usage: 837.8+ KB

In [103]:
# 필요한 라이브러리 임포트
from pycaret.classification import *

# 1. 데이터셋 설정
clf1 = setup(data = NTT_processing, target = 'ai_accuracy',index=False, remove_outliers=True, session_id=3751) # target column 이름을 지정해야 합니다.

# 2. 모델 비교
best_model = compare_models(sort='Accuracy') #8498 #531 #2699 #3751

In [ ]:
tuned_model = tune_model(best_model)

In [ ]:
best_model.feature_names_in_

In [ ]:
tuned_model

In [ ]:
final_model = finalize_model(tuned_model)

In [ ]:
save_model(final_model, './submit_files/gbc_model_1')

In [ ]:
evaluate_model(final_model)

In [ ]:
(NTT.isnull().sum() / len(NTT)) * 100

In [104]:
load_model('./submit_files/gbc_model_1')

Transformation Pipeline and Model Successfully Loaded

Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['ticket_id', 'strprotocol',
                                             'strcounts'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWr...
                                            criterion='friedman_mse', init=None,
                                            learning_rate=0.3, loss='log_loss',
                                            max_depth=3, max_features=1.0,
                                            max_leaf_nodes=None,
                                            min_impurity_decrease=0.0002,
                                            min_samples_leaf=4,
                                            min_samples_split=4,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators=90,
                                            n_iter_no_change=None,
                                            random_state=3751, subsample=1.0,
                                            tol=0.0001, validation_fraction=0.1,
                                            verbose=0, warm_start=False))],
         verbose=False)